### ISSUE TITLE
Most Images are not getting downloaded

### ISSUE THREAD

**Issue by codac** [auino/cookidump#12]
Most of the images are not getting downloaded. 
I would say ~90% of the images are not correct.

I have attached an example for those images.

Command is: 
py cookidump.py --separate-json C:\<dir>\chromedriver.exe d:\<dir>

![r12898](https://user-images.githubusercontent.com/9403626/154667351-06b2fa27-79db-488f-86e7-dc30c77b7790.jpg)

**Comment by auino** [comment]
You are right. The output `images` folder contained wrong images, although generated HTML files were still browsable correctly.
Fixed it!
Please try the new version and, if the problem is not solved, reopen the issue.

**Comment by codac** [comment]
works like a charm. confirmed.
