### ISSUE TITLE
Latest version of chromedriver removed get_element_by_XYZ

### ISSUE THREAD

**Issue by kczulko** [auino/cookidump#18]
Hi,

While I was working on [this](https://github.com/auino/cookidump/pull/17) I saw that some ~latest `chromedriver` doesn't work with this code. In general I was facing this behavior/errors: https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el

Therefore nipkgs version I used is not quite recent there.

Best regards,
Karol

**Comment by auino** [comment]
Solved in the latest version.
