### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by aly23** [auino/cookidump#2]
Someone has parsed the recipes in a readable format?
Thanks

**Comment by Tisila** [comment]
I'm now in the process of retrieving recipes and thinking of parsing it to markdown just because it is a versatile format.

**Comment by auino** [comment]
If you wish, I can add you as a contributor, to integrate your code on this repository.

**Comment by xiringuelu** [comment]
I have written a set of ruby scripts which parse the JSON files, downloading the images and creating the following HTML files:

- A launcher with all the countries available.
- All the collections (thumbnails) per country.
- All the recipes (thumbnails) per country. Useful when searching.
- All the recipes (thumbnails) per collection.
- The recipe itself (big photo, ingredients, steps, nutritional values and tips).

The downside is that the scripts are heavily dependant on a defined file structure. They use a set of defined CSS and static images.

Please let me know if you are interested and want to see some examples.

**Comment by Tisila** [comment]
Thanks @auino that would be great! My go to language is Python so I'm looking forward to play with this project. 
I don't have the best availability but will be working on it because I bought the 1 month subscription plan. =P
@xiringuelu some examples would be nice to boost the productivity ;-)

**Comment by auino** [comment]
> I have written a set of ruby scripts which parse the JSON files, downloading the images and creating the following HTML files:
> 
> * A launcher with all the countries available.
> * All the collections (thumbnails) per country.
> * All the recipes (thumbnails) per country. Useful when searching.
> * All the recipes (thumbnails) per collection.
> * The recipe itself (big photo, ingredients, steps, nutritional values and tips).
> 
> The downside is that the scripts are heavily dependant on a defined file structure. They use a set of defined CSS and static images.
> 
> Please let me know if you are interested and want to see some examples.

Do you have a dedicated GH repository? In that case, I can link it on the cookidump repository. In any case, please give us more information on your work.

**Comment by aly23** [comment]
@xiringuelu  @auino news?
Thanks

**Comment by auino** [comment]
Recipes are now provided as HTML output. Also, a list of found recipes is provided.
In virtue of this, since no updates on raw data parsing are available (not needed anymore), this issue has been closed.
