### ISSUE TITLE
selenium.common.exceptions.NosuchElementException: Message: no such element

### ISSUE THREAD

**Issue by cofw2005** [auino/cookidump#28]
I manually installed it and successfully started the command and step-by-step followed the instruction.
But at last I got such an error. Can anyone help me? What can I do to solve it? Thanks!

![image](https://github.com/auino/cookidump/assets/32097699/e2b02161-4ca2-4fce-a982-b173814e7612)

**Comment by auino** [comment]
Thank you for your message. The issue has been fixed in the latest version.

**Comment by cofw2005** [comment]
wow, that is super quick!!!
I try it right now.

**Comment by cofw2005** [comment]
It worked, great! But it can only dump 120 recipes at one time, is this as planned? I thought it will be around 1000.
