### ISSUE TITLE
New cookidoo platform

### ISSUE THREAD

**Issue by xiringuelu** [auino/cookidump#3]
I have recently noticed that in the last few days the new cookidoo platform has been progressively deployed. The authorisation - bearer steps cannot be performed anymore.

Any plan to update the script or to change the instructions to adapt to the recent changes?

Thanks for your help.

**Comment by Tisila** [comment]
Hi there!
So far I noticed the bearer key was similar but i haven't managed to login just with the key.

I did use Selenium to display an interface to login and then proceed with scraping, checkout the `new-scraping` branch. It's still in early stages but looks promissing.

**Comment by hribeir0** [comment]
That would be great! Cheers from Portugal

**Comment by Tisila** [comment]
@hribeir0 I just finished the scraping implementation.
It's now in pull request. Feel free to try it out and let me know if it has any issues.

**Comment by auino** [comment]
Closing this discussion, since a fix is in progress.
