### ISSUE TITLE
Not having to manually download chrome driver

### ISSUE THREAD

**Issue by NathanMichelDev** [auino/cookidump#33]
Hello,

First of all thanks for the work, very useful! I have a projet of using cookidoo receipes to prepare weekly meals that have good nutrional values using openai and i needed to download content from cookidoo that we use a lot at home! Worked like a charm.

However, I had trouble downloading manually the appropriate chrome driver that was compatible with my chrome version. I found that installing webdriver_manager (pip install webdriver_manager) & using

from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))

allowed me to run the cookidump without having to manually download the driver.

If you think that's interesting i can modify the repo via a PR to provide this option.

**Comment by auino** [comment]
Hi you can modify the repository and I'll merge it. Thanks.
