### ISSUE TITLE
No able to run the .py

### ISSUE THREAD

**Issue by Xpreto** [auino/cookidump#6]
Hello Gentlemen,

Did follow all the pre dump steps, that part seems perfectly fine.

Though when requesting through cmd the execution of the .py script giving the cmd as:

python cookidump.py 'C:\...\cookidump-master\cookidump-master\chromedriver.exe' 'C:\...\cookidump-master\cookidump-master\Test'

The following error occurs:

Traceback (most recent call last):
  File "C:\...\cookidump-master\cookidump-master\cookidump.py", line 21, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

To be noted that chrome does not start when running the command.

Thanks in advance for the support.

**Comment by auino** [comment]
Hi, you have to follow the step-by-step guide reported on the readme file. In particular, the output tells that you did not install the required dependencies (step 3 of the guide).
Closing the issue, as it is not an issue related to the project.

**Comment by Xpreto** [comment]
> Hi, you have to follow the step-by-step guide reported on the readme file. In particular, the output tells that you did not install the required dependencies (step 3 of the guide).
> Closing the issue, as it is not an issue related to the project.

Auino,

Thank you very much for the support.

Though i re runned the step 3 as per the guide and it referrs the following:

C:\...\cookidump-master\cookidump-master>pip install -r requirements.txt
Requirement already satisfied: selenium in c:\...\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from -r requirements.txt (line 1)) (3.141.0)
Requirement already satisfied: urllib3 in c:\users\...\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from selenium->-r requirements.txt (line 1)) (1.26.4)

**Comment by auino** [comment]
Try re-running it: I've just added `beautifulsoup4`.

**Comment by Xpreto** [comment]
I did went through Google before you commented, but yes was that step the missing element. Running ...
